### ISSUE TITLE
Some times when the bot is running properly i get this error out of no wear

### ISSUE THREAD

**Issue by VihaanReddyM** [Mid0aria/owofarmbot#12]
The error:
undefined:1
undefined
^

SyntaxError: "undefined" is not valid JSON
    at JSON.parse (<anonymous>)
    at Request._callback (D:\coding\python\discord-selfbot-owo-bot-main\owofarmbot-main\owofarmbot-main\bot.js:1062:28)
    at self.callback (D:\coding\python\discord-selfbot-owo-bot-main\owofarmbot-main\owofarmbot-main\node_modules\request\request.js:185:22)
    at Request.emit (node:events:511:28)
    at Request.onRequestError (D:\coding\python\discord-selfbot-owo-bot-main\owofarmbot-main\owofarmbot-main\node_modules\request\request.js:877:8)
    at ClientRequest.emit (node:events:511:28)
    at TLSSocket.socketErrorListener (node:_http_client:495:9)
    at TLSSocket.emit (node:events:511:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)

Node.js v20.1.0

**Comment by VihaanReddyM** [comment]
ok thanks for the feedback i will do it
