### ISSUE TITLE
Help 

### ISSUE THREAD

**Issue by Luongzz** [Mid0aria/owofarmbot#30]
`C:\Users\Yoshino\Desktop\Bot\owofarmbot-main\bot.js:1798
                        cont[0].description.includes(
                                ^

TypeError: Cannot read properties of undefined (reading 'description')
    at Request._callback (C:\Users\Yoshino\Desktop\Bot\owofarmbot-main\bot.js:1798:33)

Node.js v18.16.0`

**Comment by Luongzz** [comment]
I made a mistake in the config file so I should close the post here

**Comment by Luongzz** [comment]
`C:\Users\Yoshino\Desktop\Bot\owofarmbot-main\bot.js:1042
            var cont = bod[0].content;
                              ^

TypeError: Cannot read properties of undefined (reading 'content')
    at Request._callback (C:\Users\Yoshino\Desktop\Bot\owofarmbot-main\bot.js:1042:31)
    at self.callback (C:\Users\Yoshino\Desktop\Bot\owofarmbot-main\node_modules\request\request.js:185:22)
    at Request.emit (node:events:513:28)
    at Request.<anonymous> (C:\Users\Yoshino\Desktop\Bot\owofarmbot-main\node_modules\request\request.js:1154:10)
    at Request.emit (node:events:513:28)
    at IncomingMessage.<anonymous> (C:\Users\Yoshino\Desktop\Bot\owofarmbot-main\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (node:events:627:28)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Node.js v18.16.0`

**Comment by pinbone** [comment]
> `C:\Users\Yoshino\Desktop\Bot\owofarmbot-main\bot.js:1798 cont[0].description.includes( ^
> 
> TypeError: Cannot read properties of undefined (reading 'description') at Request._callback (C:\Users\Yoshino\Desktop\Bot\owofarmbot-main\bot.js:1798:33)
> 
> Node.js v18.16.0`

how did you fix this? i'm getting the same error

**Comment by Luongzz** [comment]
> > `C:\Users\Yoshino\Desktop\Bot\owofarmbot-main\bot.js:1798 cont[0].description.includes( ^
> > TypeError: Cannot read properties of undefined (reading 'description') at Request._callback (C:\Users\Yoshino\Desktop\Bot\owofarmbot-main\bot.js:1798:33)
> > Node.js v18.16.0`
> 
> how did you fix this? i'm getting the same error

edit config
