### ISSUE TITLE
Should i install another requests version? I don't know.

### ISSUE THREAD

**Issue by LSbyt** [Mid0aria/owofarmbot#35]
C:\Users\User\Downloads\owofarmbot-main\owofarmbot-main\bot.js:1043
            var cont = bod[0].content;
                              ^

TypeError: Cannot read properties of undefined (reading 'content')
    at Request._callback (C:\Users\User\Downloads\owofarmbot-main\owofarmbot-main\bot.js:1043:31)
    at self.callback (C:\Users\User\Downloads\owofarmbot-main\owofarmbot-main\node_modules\request\request.js:185:22)
    at Request.emit (node:events:512:28)
    at Request.<anonymous> (C:\Users\User\Downloads\owofarmbot-main\owofarmbot-main\node_modules\request\request.js:1154:10)
    at Request.emit (node:events:512:28)
    at IncomingMessage.<anonymous> (C:\Users\User\Downloads\owofarmbot-main\owofarmbot-main\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (node:events:626:28)
    at IncomingMessage.emit (node:events:524:35)
    at endReadableNT (node:internal/streams/readable:1378:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Node.js v20.4.0

**Comment by VihaanReddyM** [comment]
@Mid0aria broo you need to pull the request there is a error when ever we run the file pls be quick

**Comment by VihaanReddyM** [comment]
run
`node updater.js`
