### ISSUE TITLE
update today broke some stuff?

### ISSUE THREAD

**Issue by 420002** [Mid0aria/owofarmbot#45]
C:\Users\.......\Desktop\owofarmbot-main\bot.js:937
                        var des = cont[0].description;
                                          ^

TypeError: Cannot read properties of undefined (reading 'description')
    at Request._callback (C:\Users\........\Desktop\owofarmbot-main\bot.js:937:43)
    at self.callback (C:\Users\.........\Desktop\owofarmbot-main\node_modules\request\request.js:185:22)
    at Request.emit (node:events:514:28)
    at Request.<anonymous> (C:\Users\........\Desktop\owofarmbot-main\node_modules\request\request.js:1154:10)
    at Request.emit (node:events:514:28)
    at IncomingMessage.<anonymous> (C:\Users\........\Desktop\owofarmbot-main\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (node:events:628:28)
    at IncomingMessage.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Node.js v18.17.0

i didnt change anything and started getting this error, even played around with the settings to try and get it to work but no luck lmk if im just being special

**Comment by Mid0aria** [comment]
If your internet is slow or the owo bot is running slow, they will not work synchronously with the farm bot, then it will give this error

**Comment by 420002** [comment]
this error is spat if the extra token is used
