### ISSUE TITLE
Getting this error when running

### ISSUE THREAD

**Issue by BigSmoke2T1** [Mid0aria/owofarmbot#46]
SyntaxError: "undefined" is not valid JSON                                                                                  
at JSON.parse (<anonymous>)                                                                                             
at Request._callback (C:\Users\Administrator\Desktop\owofarmbot-main\bot.js:619:32)                                     
at self.callback (C:\Users\Administrator\Desktop\owofarmbot-main\node_modules\request\request.js:185:22)                
at Request.emit (node:events:514:28)                                                                                    
at Request.onRequestError (C:\Users\Administrator\Desktop\owofarmbot-main\node_modules\request\request.js:877:8)        
at ClientRequest.emit (node:events:514:28)                                                                              
at TLSSocket.socketErrorListener (node:_http_client:495:9)                                                              
at TLSSocket.emit (node:events:514:28)                                                                                  
at emitErrorNT (node:internal/streams/destroy:151:8)                                                                    
at emitErrorCloseNT (node:internal/streams/destroy:116:3)

**Comment by Mid0aria** [comment]
https://github.com/Mid0aria/owofarmbot/issues/11
