### ISSUE TITLE
BUG!

### ISSUE THREAD

**Issue by VihaanReddyM** [Mid0aria/owofarmbot#51]
Getting this error all the time i run the program

```
D:\coding\python\discord-selfbot-owo-bot-main\owofarmbot-main\owofarmbot-main\bot.js:937
                        var des = cont[0].description;
                                          ^

TypeError: Cannot read properties of undefined (reading 'description')
    at Request._callback (D:\coding\python\discord-selfbot-owo-bot-main\owofarmbot-main\owofarmbot-main\bot.js:937:43)
    at self.callback (D:\coding\python\discord-selfbot-owo-bot-main\owofarmbot-main\owofarmbot-main\node_modules\request\request.js:185:22)
    at Request.emit (node:events:513:28)
    at Request.<anonymous> (D:\coding\python\discord-selfbot-owo-bot-main\owofarmbot-main\owofarmbot-main\node_modules\request\request.js:1154:10)
    at Request.emit (node:events:513:28)
    at IncomingMessage.<anonymous> (D:\coding\python\discord-selfbot-owo-bot-main\owofarmbot-main\owofarmbot-main\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (node:events:627:28)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Node.js v18.16.1
```

**Comment by Mid0aria** [comment]
FIXED https://github.com/Mid0aria/owofarmbot/commit/c6aa811e9ae9a30bf39c7ec6528f1ce039fd1939
