### ISSUE TITLE
how to solve this, i can run the script on my pc, while it showed errors after i made tokens secured on replit via mobile

### ISSUE THREAD

**Issue by hawi-glitch** [Mid0aria/owofarmbot#74]
SyntaxError: Unexpected token s in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (/home/runner/Aaaa/bot.js:1577:28)
    at self.callback (/home/runner/Aaaa/node_modules/request/request.js:185:22)
    at Request.emit (node:events:513:28)
    at Request.<anonymous> (/home/runner/Aaaa/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:513:28)
    at IncomingMessage.<anonymous> (/home/runner/Aaaa/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:627:28)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
  https://replit.com/@hankyou20051229/Aaaa (secured token added)

**Comment by VihaanReddyM** [comment]
are you on mobile

**Comment by VihaanReddyM** [comment]
it is something with how to store your tokeni think or with the json file

**Comment by Mid0aria** [comment]
I may have forgotten to add the env configuration. I will fix it in the next update
